title: Navanya Palla
email: navanyapalla@gmail.com
description: >-
  Law student and aspiring litigator. Portfolio and resume for Navanya Palla.
baseurl: "" # change if you serve from a subpath
url: ""     # set to https://your-username.github.io if using user site
theme: minima
